### ISSUE TITLE
`load': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by sonots** [yuku-t/parallel-rspec#9]
I got an error like

```
/Users/naotoshi.seo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/parallel-rspec-c95d59273b0f/lib/rspec/parallel/worker.rb:74:in `load': no implicit conversion of nil into String (TypeError)
        from /Users/naotoshi.seo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/parallel-rspec-c95d59273b0f/lib/rspec/parallel/worker.rb:74:in `block in each'
        from /Users/naotoshi.seo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/parallel-rspec-c95d59273b0f/lib/rspec/parallel/worker.rb:60:in `loop'
        from /Users/naotoshi.seo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/parallel-rspec-c95d59273b0f/lib/rspec/parallel/worker.rb:60:in `each'
```

**Comment by sonots** [comment]
Maybe when, num of concurrency is larger than number of test files.
